### ISSUE TITLE
TypeError in new outbox changes

### ISSUE THREAD

**Issue by pascalzauberzeug** [zauberzeug/learning_loop_node#20]
I tried to deploy the new detector build onto U6/RB34 (the one where the image was built), but I get this error causing the container to crash.

```
detector_1    | Traceback (most recent call last):
detector_1    |   File "/app/main.py", line 6, in <module>
detector_1    |     from learning_loop_node import DetectorNode
detector_1    |   File "/usr/local/lib/python3.8/dist-packages/learning_loop_node/__init__.py", line 5, in <module>
detector_1    |     from .detector.detector_node import DetectorNode
detector_1    |   File "/usr/local/lib/python3.8/dist-packages/learning_loop_node/detector/detector_node.py", line 24, in <module>
detector_1    |     from .inbox_filter.relevance_filter import RelevanceFilter
detector_1    |   File "/usr/local/lib/python3.8/dist-packages/learning_loop_node/detector/inbox_filter/relevance_filter.py", line 4, in <module>
detector_1    |     from ..outbox import Outbox
detector_1    |   File "/usr/local/lib/python3.8/dist-packages/learning_loop_node/detector/outbox.py", line 29, in <module>
detector_1    |     class Outbox():
detector_1    |   File "/usr/local/lib/python3.8/dist-packages/learning_loop_node/detector/outbox.py", line 169, in Outbox
detector_1    |     def set_mode(self, mode: OutboxMode | str):
detector_1    | TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'type'
```

**Comment by NiklasNeugebauer** [comment]
Those damn type annotations!
This needs to be a Union and probably String and I need to start using Python 3.8 for testing. Will fix it first thing tomorrow morning!

**Comment by NiklasNeugebauer** [comment]
10.8 ist released und für orins gebaut

**Comment by pascalzauberzeug** [comment]
Tested on U4/RB28, works! Thanks @NiklasNeugebauer
